/**
* @author:     Stefan Meier
* @version:    20110710
*
* This is an autogenerated file to transfer language settings
* from server to client
*/
<?php
require_once('application/GlobalRegistry.php');
require_once('application/LanguageLinker.php');

session_start();

$globalRegistry = $_SESSION["GlobalRegistry"];
$languageLinker = $globalRegistry->languageLinker;

$keys = array(
"calendar-message-confirm-repeat-update" => $languageLinker->resourceBundle->get("calendar-message-confirm-repeat-update"),
"calendar-message-confirm-repeat-delete" => $languageLinker->resourceBundle->get("calendar-message-confirm-repeat-delete"),
"calendar-event-delete" => $languageLinker->resourceBundle->get("calendar-event-delete"),
"calendar-event-save" => $languageLinker->resourceBundle->get("calendar-event-save"),
"calendar-event-cancel" => $languageLinker->resourceBundle->get("calendar-event-cancel"),
"application-title" => $languageLinker->resourceBundle->get("application-title"),
"calendar-information" => $languageLinker->resourceBundle->get("calendar-information"),
"calendar-choice" => $languageLinker->resourceBundle->get("calendar-choice"),
"calendar-goTo" => $languageLinker->resourceBundle->get("calendar-goTo"),
"calendar-message-confirm-repeat-all" => $languageLinker->resourceBundle->get("calendar-message-confirm-repeat-all"),
"calendar-message-confirm-repeat-this" => $languageLinker->resourceBundle->get("calendar-message-confirm-repeat-this"),
"calendar-event-new" => $languageLinker->resourceBundle->get("calendar-event-new"),
"calendar-event-edit" => $languageLinker->resourceBundle->get("calendar-event-edit"),
"calendar-message-check" => $languageLinker->resourceBundle->get("calendar-message-check"),
"calendar-error-time" => $languageLinker->resourceBundle->get("calendar-error-time"),
"calendar-error-unavailable" => $languageLinker->resourceBundle->get("calendar-error-unavailable"),
"calendar-error-user" => $languageLinker->resourceBundle->get("calendar-error-user"),
"calendar-error-access" => $languageLinker->resourceBundle->get("calendar-error-access"),
"calendar-error-room" => $languageLinker->resourceBundle->get("calendar-error-room"),
"calendar-error-action" => $languageLinker->resourceBundle->get("calendar-error-action"),
"calendar-error-invalid" => $languageLinker->resourceBundle->get("calendar-error-invalid"),
"calendar-error-dateFormat" => $languageLinker->resourceBundle->get("calendar-error-dateFormat"),
"calendar-error-system" => $languageLinker->resourceBundle->get("calendar-error-system"),
"calendar-message-confirm-button-ok" => $languageLinker->resourceBundle->get("calendar-message-confirm-button-ok"),
"calendar-message-confirm-button-yes" => $languageLinker->resourceBundle->get("calendar-message-confirm-button-yes"),
"calendar-message-confirm-button-no" => $languageLinker->resourceBundle->get("calendar-message-confirm-button-no"),
"calendar-message-confirm-button-allFuture" => $languageLinker->resourceBundle->get("calendar-message-confirm-button-allFuture"),
"calendar-message-confirm-button-thisEvent" => $languageLinker->resourceBundle->get("calendar-message-confirm-button-thisEvent")
);
?>
<?php 
foreach ($keys as $key => $value) {
	echo "resourceBundle[\"$key\"] = \"$value\";\n";
}

for($i = 1; $i <= 12; $i++) {
	echo "resourceBundle[\"month-$i-full\"] = \"{$languageLinker->resourceBundle->get("month-$i-full")}\";\n";
	echo "resourceBundle[\"month-$i-short\"] = \"{$languageLinker->resourceBundle->get("month-$i-short")}\";\n";
}

for ($i = 1; $i<= 7; $i++) {
	echo "resourceBundle[\"day-$i-full\"] = \"{$languageLinker->resourceBundle->get("day-$i-full")}\";\n";
	echo "resourceBundle[\"day-$i-short\"] = \"{$languageLinker->resourceBundle->get("day-$i-short")}\";\n";
}
?>